### ISSUE TITLE
Have finesse-backend point to index finesse-public-guidance-index with semantic search

### ISSUE THREAD

**Issue by rngadam** [ai-cfia/azure-db#15]
@cfiaGeetika 

end goal is to be able to point whatever deployment we have (Frontend, backend) to the selected version of the search index.

probably separated deployment from finesse-public-website 

(finesse-guidance.inspection.alpha.canada.ca)

...or do we want labels identifying guidance documents as a collection?

**Comment by ThomasCardin** [comment]
Current Deployments:

There are currently two deployments, both pointing to a specific index.

For the guidance index:

- Frontend: https://finesse-guidance.ninebasetwo.xyz/api
- Backend: https://finesse-guidance.ninebasetwo.xyz/

For the azure index (not currently functional. After discussion with @k-allagbe, guidance seems to be a higher priority than the azure index):

- https://finesse.ninebasetwo.xyz/
- https://finesse.ninebasetwo.xyz/api

Regarding the domain name:

- An issue is open to track the changes.
- It will be completed once our migration to Azure is complete.
- Github Issue Link: https://github.com/ai-cfia/howard/issues/36

**Comment by k-allagbe** [comment]
Closing this issue as fixed.
