### ISSUE TITLE
Create a package for Azure Blob Storage interactions in azure-db

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/azure-db#3]
Develop a Python package for Azure Blob Storage to facilitate blob operations like uploading, downloading, and managing blobs, with a focus on adding metadata during uploads.

### Tasks
1. **Package Structure**: Establish a modular package structure.
2. **Connection Utilities**: Functions for Azure Blob Storage connections.
3. **Blob Operations**: Implement upload, download, and blob management functions. Ensure upload functions include metadata handling capabilities.
4. **Error Handling and Security**: Ensure robust error handling and secure access key management.
5. **Performance Optimization**: Optimize for large files and high throughput.
6. **Testing**: Develop a comprehensive test suite.
7. **Documentation**: Provide clear usage documentation.

### Acceptance Criteria
- **Ease of Installation**: Package installable via pip.
- **Core Functionalities**: Seamless interaction with Azure Blob Storage.
- **Security and Performance**: Adherence to security best practices and high performance.
- **Testing**: Comprehensive tests for functionality and stability.
- **Documentation**: Detailed and user-friendly documentation.

**Comment by ibrahim-kabir** [comment]
No longer relevant

**Comment by rngadam** [comment]
> No longer relevant

Why no longer relevant? Seems like it was completed and there's a setup.py in azure-db/azure-ai-search to turn this into a package and used from finesse-backend?

https://github.com/ai-cfia/finesse-backend/blob/95788cbdfbb2f31bb7b70d4a22c3a0b42de7c391/requirements.txt#L6

**Comment by k-allagbe** [comment]
> > No longer relevant
> 
> Why no longer relevant? Seems like it was completed and there's a setup.py in azure-db/azure-ai-search to turn this into a package and used from finesse-backend?
> 
> https://github.com/ai-cfia/finesse-backend/blob/95788cbdfbb2f31bb7b70d4a22c3a0b42de7c391/requirements.txt#L6
> 
> To me looks like @k-allagbe completed part of the work.

I meant this issue to have a centralized way of interacting with our BLOB storages. It is actually a non issue because the azure python package is comprehensive and easy to use enough not to need this. This would not add value.
